#!/bin/bash

function maven 
{
#    mvn clean install -Dmaven.test.skip=true -X -e -P pangyo6f
    mvn clean install -Dmaven.test.skip=true -X -e -P $1
}

function mvn_build 
{
#    mvn clean install -Dmaven.test.skip=true -X -e -P pangyo6f
    cd ~/tros-root;
    mvn clean install -Dmaven.test.skip=true -X -e -P $1
}

function lui 
{ 
    cd ~/tros/ui/app 
}

function lcore 
{ 
    cd ~/tros/core 
}

function apt.g
{ 
    apt-get install $1
}

function apt.s
{ 
    apt-cache search $1
}

function r.c.ui() {
    PW=cloud000@
expect <<EOF
        set timeout -1
        spawn scp cloud@c.ui:$1 .
        sleep 1
        expect "password:"
                send "$PW\r"
        expect eof
EOF
}
